### ISSUE TITLE
new version needed

### ISSUE THREAD

**Issue by nolith** [stouset/version#22]
Do you have a plan to public a new release to rubygems.org including hg (and svn) support?

**Comment by damc-dev** [comment]
It appears that the pull requests for hg and svn support have been merged
* [Mercurial support #12](https://github.com/stouset/version/pull/12)
* [SVN support #13](https://github.com/stouset/version/pull/13)

Would you be able to release a new version to rubygems.org?

**Comment by stouset** [comment]
1.1 is released
