### ISSUE TITLE
Would it be possible to switch gem ownership?

### ISSUE THREAD

**Issue by bkuhlmann** [stouset/version#28]
## Overview

I was looking over this project and wanted to know if it was still maintained as there hasn't been much activity in ~2 years. I ask because I'm the author of [Versionaire](https://github.com/bkuhlmann/versionaire) which is a similar implementation (although, doesn't have all of the Rake support but could look into adding it if that was a concern). I'd be interesting in claiming the gem namespace for `Version` if possible. This would provide an implementation that is semantic and immutable by nature.

Anyway, if this is of interest, let me know. I wanted to reach out in case project is no longer maintained or actively worked on. Thanks!

**Comment by stouset** [comment]
It’s not actively maintained because it’s pretty much feature-complete as
far as I’m concerned.

I’m not really interested in transferring ownership of the gem of the
intent is to effectively rename Versionaire to Version, which it sounds
like is what you’re asking. If that’s not your intent, what
features/changes are you hoping to introduce?

**Comment by bkuhlmann** [comment]
:bow: @stouset. Yeah, I was hoping to claim the [RubyGems version namespace](https://rubygems.org/gems/version). I've been wanting to introduce a `Version` object that would allow people to use semantic, immutable versions that is shorter than `Versionaire::Version`. It would also allow Ruby developers to have a `Version()` conversion/casting function similar to `String()`, `Integer()`, etc. as already exists in the Ruby language.  I was mostly curious to check if this namespace was being actively used and it sounds like it is. :sweat_smile:
